[package]
name = "cli"
version = "0.1.0"
authors = ["beltegeuse <adrien.gruson@gmail.com>"]
edition = "2018"

[dependencies]
clap = "*"
genetic-drawing = { path = "../../" }
rand = "*"
image = "*"
pbr = "*"

# For flamegraph (r)
#[profile.release]
# debug = true